### ISSUE TITLE
Error: Cannot find module 'change-case'

### ISSUE THREAD

**Issue by evert-arias** [smakosh/gatsby-theme-portfolio#2]
I'm getting the following error when running `gatsby develop`:

**Error: Cannot find module 'change-case'**

![Screenshot_2](https://user-images.githubusercontent.com/30301607/70649906-111d0d00-1c1c-11ea-93de-6019458805d7.png)

The error has to do with the required plugin **gatsby-mdx**.

**Comment by evert-arias** [comment]
Module [gatsby-mdx](https://www.npmjs.com/package/gatsby-mdx) as been deprecated use [gatsby-plugin-mdx](https://www.npmjs.com/package/gatsby-plugin-mdx) instead.

![Screenshot_4](https://user-images.githubusercontent.com/30301607/70657651-34e74f80-1c2a-11ea-896d-404d5b1745d4.png)

**Comment by smakosh** [comment]
I'm unable to reproduce the issue @evert-arias, can you share your codebase to investigate?

**Comment by evert-arias** [comment]
Hi @smakosh 
I've tried again after a couple days and that issue has gone. I suspect that it was a problem in my development environment at the time I was testing. Thank you for your prompt response.
